### ISSUE TITLE
delete unused page tip

### ISSUE THREAD

**Issue by patrycjapicha** [gsysko/Ztart#30]
we can add the tip to designers that it is not necessary to keep empty pages in the file 

Insight
Some figma files have many empty pages kept - when someone jumped in file it is confusing why few pages are empty, if it a bug or it is empty file

**Comment by gsysko** [comment]
Hello @patrycjapicha , I've added a small template for optional pages and and included a sticky that gives a tip about deleting the page, if unneeded. Let me know what you think and if other improvements can be made...
<img width="354" alt="image" src="https://user-images.githubusercontent.com/1911327/193554638-0516d02c-3952-493e-9d29-f2e2d0e6135f.png">

**Comment by patrycjapicha** [comment]
Perfect! :)
